roles:
  "auth:anon":
    priority: 0
    permissions: []
  "auth:user":
    priority: 1
    inherits:
      - "auth:anon"
    permissions:
      - "modules:get"
      - "modules:versions:list"
      - "projects:create"
      - "projects:delete"
      - "projects:list"
      - "projects:update"
      - "schemas:create"
      - "schemas:generate"
      - "schemas:get"
      - "schemas:rewrite"
      - "schemas:versions:list"
  "auth:admin":
    priority: 2
    inherits:
      - "auth:user"
    permissions: []
  "auth:superadmin":
    priority: 3
    inherits:
      - "auth:admin"
    permissions: []
